### PR TITLE
Feature/enable proxy connection to fs server

### PR DESCRIPTION
**Pull request by sosswa**
As discussed in #12 (https://github.com/e-Spirit/FSDevTools/issues/12) we have added proxy support for the FS-Dev Tools using the already used Connection Manager.

Therefore only proxy host and port can be configured. Using a proxy with authentication is not possible since the FirstSpirit connection manager does not support this.

Please review and merge into the official release of the FS-Dev Tools since other customer may want this to.

If you have any questions just contact me.

Greetings
Sandro

### CODE REVIEW

**Comment by Martin-Aulich** [comment]
Tested the updated fs-cli in our Bosch environment incl. localhost CNTLM proxy. Worked fine.

**Comment by sosswa** [comment]
Hey e-Spirit, how is the status of the merge of this pull request?
We and our customer would like it to be in the official DEV-Tools release!

**Comment by Martin-Aulich** [comment]
+1 from my side. @pernpeintner-espirit: what about merging the PR?

**Comment by Martin-Aulich** [comment]
@pm-espirit, @boesebeck-espirit : this PR is now open since more than two months without any feedback or merge from your side. 

I'd expect a more active collaboration, especially since developer experience is a focus topic of you. We actually went the extra mile and developed a feature which should be standard for any large customer (support of proxies) and now it even feels like we don't get any support in bringing merging this back to the core product.

**Comment by gockel-e-spirit** [comment]
Hello @Martin-Aulich , hello @sosswa 

you're absolutely right. Due to internal restructuring, communication has suffered greatly here and I apologize for that.

We are now processing the pull request under the internal ticket id DEVEX-278.

We will keep you informed about the further process.

**Comment by Martin-Aulich** [comment]
Hello @gockel-e-spirit,

thanks for the update and the efforts on your side :).

Cheers,
Martin

**Comment by magrosskopf** [comment]
Hello
is this feature available in the latest release?

**Comment by kafmann-e-spirit** [comment]
Hello @magrosskopf  @Martin-Aulich @sosswa 
This PR has been merged with the commits [e350780c4b6411374a72bf55ad3d745750490e0d](e350780c4b6411374a72bf55ad3d745750490e0d) , [2ee57658165cf4ee6339c3529373e9255d8657d1](2ee57658165cf4ee6339c3529373e9255d8657d1) & [fbf0ac4232d12fb448433e416f5e7fb19124c844](fbf0ac4232d12fb448433e416f5e7fb19124c844) and is included in [Release 2.4.761](https://github.com/e-Spirit/FSDevTools/releases/tag/2.4.761).

However, we modified some parameter and method names to clarify that these proxy settings only apply for HTTP/HTTPS connections (not for SOCKET).


Thanks for your contribution on this project!

**Pull request closed without merging**
