### PR TITLE
updated Airline version to 2.7.2

### PR DESCRIPTION
**Pull request by Christian-Brockmann**
Hi, 

i have updated the version of airline to the version 2.7.2 to use and override a TypeConverterProvider.

Best regards
Christian

### CODE REVIEW

**Comment by kafmann-e-spirit** [comment]
Hi Christian,

first of all: thanks for your pull-request! We are currently reviewing your pull-request (ticket id DEVEX-339) and will try to ship this changes as soon as possible.

**Comment by Prophet96ix** [comment]
Hi Christian,

I have reviewed your PR and found issues:

The CliTest will **fail** after your commit because of an IllegalArgumentException (There are duplicate command names).
Please correct your @Command annotations to use **distinct command names**.

One possible solution would be to change the command name in 
_`_fsdevtools/fsdevtools-cli/src/test/java/com/espirit/moddev/cli/testcommands/reflectiontest/CommandWithNonStringDescriptionMethod.java_`_

Therefore I cannot accept your PR in this stage, sorry for the inconvenience

**Comment by Christian-Brockmann** [comment]
Hi Christian, 

thank you for the information. I got an email that the PR was reviewed, but there occurred some problems in the CLITest:

Please correct your @command annotations to use distinct command names.
One possible solution would be to change the command name in
_fsdevtools/fsdevtools-cli/src/test/java/com/espirit/moddev/cli/testcommands/reflectiontest/CommandWithNonStringDescriptionMethod.java_

Unfortunately I was not able to build the project with gradle and run the tests. But it just seems to be a duplicate name in the CLITest. 
Is it possible that you check once, if the duplicate name is the problem and the dependency of the airline tool can be updated? We need the newer version, so that there converters can be used, which directly converts the passed parameters from the console. 

Many thanks in advance and best regards
Christian

**Comment by kafmann-e-spirit** [comment]
Hi Christian, thanks for your information. 

We already fixed those errors in the PR and can confirm that a simple name change fixes the problem. Your PR is on a good way :)

**Comment by Christian-Brockmann** [comment]
Hi Christian, 

thanks for the informationen. That sounds very good :)

Many thanks in advance and best regards
Christian

**Comment by wagner-e-spirit** [comment]
Hi Christian,

this PR (and other dependency updates) has been pushed to master with commit [
808399f](https://github.com/e-Spirit/FSDevTools/commit/808399f67c40b694b778c1ce01a95162db8eae9d).

You can find the changes in [Release 2.5.6](https://github.com/e-Spirit/FSDevTools/releases/tag/2.5.6).

Thanks for your contribution :)

**Pull request closed without merging**
